// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TextCommandFramework;

#nullable disable

namespace TextCommandFramework.Migrations
{
    [DbContext(typeof(BotContext))]
    [Migration("20240319155943_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.3");

            modelBuilder.Entity("TextCommandFramework.Profile", b =>
                {
                    b.Property<string>("ProfileId")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("DiscordId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Experience")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InventorySpace")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Money")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserListId")
                        .HasColumnType("TEXT");

                    b.HasKey("ProfileId");

                    b.HasIndex("UserListId");

                    b.ToTable("Profile");
                });

            modelBuilder.Entity("TextCommandFramework.UserList", b =>
                {
                    b.Property<string>("UserListId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserListId");

                    b.ToTable("List");
                });

            modelBuilder.Entity("TextCommandFramework.Profile", b =>
                {
                    b.HasOne("TextCommandFramework.UserList", null)
                        .WithMany("Profiles")
                        .HasForeignKey("UserListId");
                });

            modelBuilder.Entity("TextCommandFramework.UserList", b =>
                {
                    b.Navigation("Profiles");
                });
#pragma warning restore 612, 618
        }
    }
}
